import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
<<<<<<< HEAD
import { ToasterWrapper } from "@/components/toaster-wrapper";
 
 
=======
import Footer from "@/components/Footer";

>>>>>>> 6b9677d358f924e20faa2e8d3cd14743e04ffdab
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Navbar/>
        {children}
<<<<<<< HEAD
        <ToasterWrapper />
=======
        <Footer/>
>>>>>>> 6b9677d358f924e20faa2e8d3cd14743e04ffdab
      </body>
    </html>
  );
}
